# Environnement Web de developpement en PHP 7.0.13 avec Apache
version: '2'
services:

  # Web Server PHP 5.6 + Apache 2
  web:
    restart: always
    build: docker/php5apache
    container_name: web-afl
    ports:
       - "80:80" # Redirection des portes entre l'hote et Docker
    volumes:
       - /home/adebril/src/php5:/mnt/filer/php5
       - ./logs:/var/log/apache2
       - ./conf/apache/vhosts:/etc/apache2/sites-enabled # Emplacement de VHOST Apache
       - ./conf/php/php.ini:/usr/local/etc/php/conf.d/30-custom.ini # PHP ini custom
    environment:
       - ALLOW_OVERRIDE=true
    links:
       - localdb:localdb
       - maildev:maildev

#  # Web Server NGinx
#  web:
#    image: nginx
#    ports:
#        - "81:80"
#    container_name: web
#    volumes:
#        - ./conf/nginx:/etc/nginx/conf.d
#        - ./projects:/var/www/html
#    links:
#        - php:php
#
#  # PHP 7.0.13 FPM
#  php:
#    build: docker/php7fpm
#    container_name: php
#    volumes:
#        - ./projects:/var/www/html
#        - ./conf/php/php.ini:/usr/local/etc/php/php.ini
#    links:
#        - db:db
#        - maildev:maildev

  # PHP 5.6 FPM
#  php:
#    build: docker/php5.6fpm
#    container_name: php
#    volumes:
#        - ./projects:/var/www/html
#        - ./conf/php/php.ini:/usr/local/etc/php/php.ini
#    links:
#        - db:db
#        - maildev:maildev

  # Database MySQL
  localdb:
      restart: always
      image: mariadb
      container_name: localdb
      volumes:
        - /var/data/mariadb:/var/lib/mysql # Commenter la ligne des volumes pour une base de données non persistente
        - /var/data/sql:/var/sql
      ports:
        - "13306:3306"
      environment:
       - MYSQL_ROOT_PASSWORD=root # Mot de passe par defaut pour l'utisateur root

  # To create email during devloppement
  maildev:
      restart: always
      image: djfarrelly/maildev
      container_name: maildev
      ports:
        - "1080:80"

  # PHP Package management
  composer:
    restart: always
    image: composer/composer

  # Node / Bower / Grunt
  nodejs-grunt-bower:
    restart: always
    image: digitallyseamless/nodejs-bower-grunt

  # PhpMyAdmin
  phpmyadmin:
    restart: always
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    links:
      - localdb:db
    ports:
      - 8000:80
    volumes:
      - /sessions
